import Head from 'next/head'
import Form from '@/components/Form'

export default function Home () {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Esta es mi primera página web con NextJS</h1>
        <h2>Déjame un comentario y con gusto te responderé</h2>
        <Form />
      </div>
    </>
  )
}
